### ISSUE TITLE
Progress tracker

### ISSUE THREAD

**Issue by boreq** [boreq/epkk#1]
General:
- [x] accurate taxiway and runway markings
- [x] accurate stands
- [x] accurate runway lights
- [ ] support for builtin refueling etc

Buildings:
- [x] administration
- [x] three hangars
- [ ] other buildings
